"use client";

import { useState } from "react";
import { useFormContext } from "react-hook-form";
import { Upload, Trash2, Loader2, FileText } from "lucide-react";
import { pickFile } from "@/lib/utils/pick-file";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import type { DraftoProject } from "@/lib/schema";

// PDF Generation dialog for the Delhi HC writ petition. Every drafted component
// is always generated by the app — this dialog only collects the upload-only
// filing documents and the signed/executed versions that replace the generated
// clean affidavit / vakalatnama. It never overrides a generated document.
export function WpPdfGenerationDialog({
  children,
  onGenerate,
  isPending,
}: {
  children: React.ReactNode;
  onGenerate: () => void;
  isPending?: boolean;
}) {
  const form = useFormContext<DraftoProject>();
  const [open, setOpen] = useState(false);

  const slot = (key: string, label: string, hint: string) => {
    const val: any = form.watch(`wp.uploads.${key}` as any);
    const has = val?.file instanceof File || !!val?.filePath;
    const fileName = val?.file?.name || (val?.filePath ? String(val.filePath).split(/[\\/]/).pop() : "");
    const pick = async () => {
      const f = await pickFile();
      if (f) {
        form.setValue(`wp.uploads.${key}.file` as any, f, { shouldDirty: true });
        form.setValue(`wp.uploads.${key}.filePath` as any, (f as any).path);
      }
    };
    const clear = () => {
      form.setValue(`wp.uploads.${key}.file` as any, undefined, { shouldDirty: true });
      form.setValue(`wp.uploads.${key}.filePath` as any, undefined);
    };
    return (
      <div className="flex items-center justify-between gap-2 rounded-md border p-2">
        <div className="min-w-0">
          <p className="text-xs font-medium">{label}</p>
          <p className="truncate text-[11px] text-muted-foreground">{has ? fileName : hint}</p>
        </div>
        <div className="flex shrink-0 items-center gap-1">
          <Button type="button" size="sm" variant="outline" onClick={pick}><Upload className="mr-1 h-3.5 w-3.5" />{has ? "Replace" : "Upload"}</Button>
          {has && <Button type="button" size="icon" variant="ghost" className="h-7 w-7 text-destructive" onClick={clear}><Trash2 className="h-3.5 w-3.5" /></Button>}
        </div>
      </div>
    );
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Generate Writ Petition Paperbook</DialogTitle>
          <DialogDescription>
            Every drafted document is generated automatically. Upload the filing
            documents and any signed/executed versions to merge into the PDF.
          </DialogDescription>
        </DialogHeader>
        <div className="max-h-[55vh] space-y-2 overflow-auto pr-1">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Filing documents</p>
          {slot("courtFee", "Court Fee", "e-Court Fee receipt (PDF or image).")}
          {slot("proofOfService", "Proof of Service", "Advance-service email / acknowledgement.")}
          <p className="pt-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Signed / executed copies</p>
          <p className="text-[11px] text-muted-foreground">Optional — when uploaded, these replace the generated clean version in the paper-book.</p>
          {slot("signedAffidavit", "Affidavit (to the Petition)", "Notarised affidavit PDF.")}
          {slot("signedVakalatnama", "Vakalatnama", "Signed / stamped vakalatnama PDF.")}
        </div>
        <DialogFooter>
          <Button type="button" onClick={() => { onGenerate(); setOpen(false); }} disabled={isPending}>
            {isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin" /> : <FileText className="mr-1 h-4 w-4" />}
            Generate Paperbook (PDF)
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
