"use client";

import { useEffect, useState } from "react";
import { useFormContext } from "react-hook-form";
import { Upload, Trash2, Loader2, FileText, AlertTriangle, OctagonAlert, CheckCircle2, ArrowUp, ArrowDown } from "lucide-react";
import { pickFile } from "@/lib/utils/pick-file";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { OcrOption } from "./ocr-option";
import type { DraftoProject } from "@/lib/schema";
import { wpPreflight } from "@/lib/wp/wp-preflight";
import { wpFrontMatterOrder } from "@/lib/wp/wp-actions";
import { useEntitlement, useExportPermission } from "@/providers/entitlement-provider";

const FRONT_LABELS: Record<"notice" | "urgency" | "memo", string> = {
  notice: "Notice of Motion",
  urgency: "Urgency Application",
  memo: "Memo of Parties",
};

// PDF Generation dialog for the Delhi HC writ petition. Every drafted component
// is always generated by the app — this dialog collects the upload-only filing
// documents and the signed/executed versions that replace the generated clean
// affidavit / vakalatnama, lets the user order the front matter, and runs the
// pre-flight checks. Issues never block generation (a partial draft may be
// wanted), but every silent failure mode is surfaced first.
export function WpPdfGenerationDialog({
  children,
  onGenerate,
  isPending,
}: {
  children: React.ReactNode;
  onGenerate: (opts?: { ocr?: boolean }) => void;
  isPending?: boolean;
}) {
  const form = useFormContext<DraftoProject>();
  const [open, setOpen] = useState(false);
  // Windows-only; the control disables itself on a Mac.
  const [ocr, setOcr] = useState(false);
  const { openManageSubscription } = useEntitlement();
  // Both questions: subscription in good standing, and this court on the plan.
  const permission = useExportPermission("WritPetitionDHC");
  const canExport = permission.allowed;

  // Mayur's "Compile" button opens the paperbook dialog for the active mode;
  // this dialog only renders in WP mode, so listening here is safe.
  useEffect(() => {
    const openFromAssistant = () => setOpen(true);
    window.addEventListener("drafto-open-paperbook", openFromAssistant);
    return () => window.removeEventListener("drafto-open-paperbook", openFromAssistant);
  }, []);

  const slot = (key: string, label: string, hint: string) => {
    const val: any = form.watch(`wp.uploads.${key}` as any);
    const has = val?.file instanceof File || !!val?.filePath;
    const fileName = val?.file?.name || (val?.filePath ? String(val.filePath).split(/[\\/]/).pop() : "");
    const pick = async () => {
      const f = await pickFile();
      if (f) {
        form.setValue(`wp.uploads.${key}.file` as any, f, { shouldDirty: true });
        form.setValue(`wp.uploads.${key}.filePath` as any, (f as any).path);
      }
    };
    const clear = () => {
      form.setValue(`wp.uploads.${key}.file` as any, undefined, { shouldDirty: true });
      form.setValue(`wp.uploads.${key}.filePath` as any, undefined);
    };
    return (
      <div className="flex items-center justify-between gap-2 rounded-md border p-2">
        <div className="min-w-0">
          <p className="text-xs font-medium">{label}</p>
          <p className="truncate text-[11px] text-muted-foreground">{has ? fileName : hint}</p>
        </div>
        <div className="flex shrink-0 items-center gap-1">
          <Button type="button" size="sm" variant="outline" onClick={pick}><Upload className="mr-1 h-3.5 w-3.5" />{has ? "Replace" : "Upload"}</Button>
          {has && <Button type="button" size="icon" variant="ghost" className="h-7 w-7 text-destructive" onClick={clear}><Trash2 className="h-3.5 w-3.5" /></Button>}
        </div>
      </div>
    );
  };

  // Front-matter ordering (Notice / Urgency / Memo — everything else is fixed).
  const watchedOrder = form.watch("wp.frontMatterOrder");
  void watchedOrder; // subscribe so the arrows re-render on move
  const order = wpFrontMatterOrder(form.getValues());
  const move = (index: number, dir: -1 | 1) => {
    const next = [...order];
    const target = index + dir;
    if (target < 0 || target >= next.length) return;
    [next[index], next[target]] = [next[target], next[index]];
    form.setValue("wp.frontMatterOrder", next, { shouldDirty: true });
  };

  // Pre-flight — recomputed while open (upload/order changes re-render via the
  // watches above; the dialog opens fresh for everything else).
  const issues = open ? wpPreflight(form.getValues()) : [];
  const errors = issues.filter(i => i.severity === "error");

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Generate Writ Petition Paperbook</DialogTitle>
          <DialogDescription>
            Every drafted document is generated automatically. Upload the filing
            documents and any signed/executed versions to merge into the PDF.
          </DialogDescription>
        </DialogHeader>
        <div className="max-h-[55vh] space-y-2 overflow-auto pr-1">
          <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Front matter order</p>
          <div className="space-y-1">
            {order.map((k, i) => (
              <div key={k} className="flex items-center justify-between rounded-md border px-2 py-1">
                <span className="text-xs">{i + 1}. {FRONT_LABELS[k]}</span>
                <span className="flex items-center gap-0.5">
                  <Button type="button" size="icon" variant="ghost" className="h-6 w-6" disabled={i === 0} onClick={() => move(i, -1)}><ArrowUp className="h-3.5 w-3.5" /></Button>
                  <Button type="button" size="icon" variant="ghost" className="h-6 w-6" disabled={i === order.length - 1} onClick={() => move(i, 1)}><ArrowDown className="h-3.5 w-3.5" /></Button>
                </span>
              </div>
            ))}
          </div>

          <p className="pt-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Filing documents</p>
          {slot("courtFee", "Court Fee", "e-Court Fee receipt (PDF or image).")}
          {slot("proofOfService", "Proof of Service", "Advance-service email / acknowledgement.")}
          <p className="pt-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Signed / executed copies</p>
          <p className="text-[11px] text-muted-foreground">Optional — when uploaded, these replace the generated clean version in the paper-book.</p>
          {slot("signedAffidavit", "Affidavit (to the Petition)", "Notarised affidavit PDF.")}
          {slot("signedVakalatnama", "Vakalatnama", "Signed / stamped vakalatnama PDF.")}

          <p className="pt-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Pre-flight check</p>
          {issues.length === 0 ? (
            <p className="flex items-center gap-1.5 text-xs text-muted-foreground"><CheckCircle2 className="h-3.5 w-3.5 text-green-600" />No issues found.</p>
          ) : (
            <ul className="space-y-1">
              {issues.map((issue, i) => (
                <li key={i} className={`flex items-start gap-1.5 text-[11px] leading-snug ${issue.severity === "error" ? "text-destructive" : "text-amber-600 dark:text-amber-500"}`}>
                  {issue.severity === "error"
                    ? <OctagonAlert className="mt-0.5 h-3 w-3 shrink-0" />
                    : <AlertTriangle className="mt-0.5 h-3 w-3 shrink-0" />}
                  <span>{issue.message}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
        <div className="border-t pt-2">
          <OcrOption checked={ocr} onChange={setOcr} disabled={isPending} />
        </div>
        <DialogFooter className="flex-col items-stretch gap-2 sm:flex-col sm:items-stretch">
          {!canExport && (
            <p className="text-[11px] text-destructive">
              {permission.reason === "court"
                ? "Writ Petitions are not included in your plan, so this paper-book cannot be generated. "
                : "Paperbook generation is disabled because your subscription isn’t active. "}
              <button type="button" className="underline" onClick={openManageSubscription}>
                {permission.reason === "court" ? "Upgrade" : "Renew"}
              </button>{" "}to continue.
            </p>
          )}
          <Button
            type="button"
            variant={errors.length ? "destructive" : "default"}
            onClick={() => { onGenerate({ ocr }); setOpen(false); }}
            disabled={isPending || !canExport}
          >
            {isPending ? <Loader2 className="mr-1 h-4 w-4 animate-spin" /> : <FileText className="mr-1 h-4 w-4" />}
            {errors.length ? `Generate anyway (${errors.length} issue${errors.length === 1 ? "" : "s"})` : "Generate Paperbook (PDF)"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
